"""
Predefined simulation scenarios for the Historical Strategy Intelligence System.
Each scenario represents a realistic historical or hypothetical combat situation.
"""

from typing import Dict, Any

SCENARIOS: Dict[str, Dict[str, Any]] = {
    "blitzkrieg_plains": {
        "name": "Blitzkrieg on the Plains",
        "description": "Rapid armored penetration across open plains against a conventional defender with inferior technology.",
        "attacker_strategy": "Blitzkrieg",
        "defender_strategy": "Conventional",
        "terrain": "Plains",
        "force_ratio": 1.5,
        "technology_gap": 1.5,
        "supply_lines": 0.9,
        "morale": 0.85,
        "weather": "Clear",
        "historical_examples": [
            "German invasion of France (1940)",
            "Operation Barbarossa opening phase (1941)",
            "Israeli Six-Day War armored operations (1967)",
            "Coalition left hook in Gulf War (1991)",
        ],
        "context": "Classic armored blitzkrieg scenario where technological superiority and speed overwhelm static defenses.",
        "expected_victor": "Attacker",
        "notes": "High attacker advantage. Defender must achieve rapid encirclement or break supply lines to counter.",
    },
    "guerrilla_forest": {
        "name": "Guerrilla War in the Forest",
        "description": "Irregular forces using forest terrain for hit-and-run attacks against a conventional army.",
        "attacker_strategy": "Guerrilla",
        "defender_strategy": "Conventional",
        "terrain": "Forest",
        "force_ratio": 0.4,
        "technology_gap": -1.0,
        "supply_lines": 0.6,
        "morale": 0.9,
        "weather": "Rain",
        "historical_examples": [
            "Vietnam War jungle campaigns",
            "Partisan warfare in Yugoslavia (WWII)",
            "FARC operations in Colombian jungle",
            "Viet Minh against French in Indochina",
        ],
        "context": "Asymmetric conflict where guerrillas leverage home terrain advantage to negate conventional superiority.",
        "expected_victor": "Attacker (Guerrilla)",
        "notes": "Despite technological inferiority, forest terrain and high morale give guerrillas decisive advantage.",
    },
    "siege_urban": {
        "name": "Urban Siege Operation",
        "description": "Besieging force attempts to capture a heavily fortified urban center defended by determined troops.",
        "attacker_strategy": "Siege",
        "defender_strategy": "Attrition",
        "terrain": "Urban",
        "force_ratio": 2.0,
        "technology_gap": 0.5,
        "supply_lines": 0.7,
        "morale": 0.75,
        "weather": "Clear",
        "historical_examples": [
            "Battle of Stalingrad (1942-43)",
            "Siege of Leningrad (1941-44)",
            "Battle of Fallujah (2004)",
            "Siege of Sarajevo (1992-96)",
        ],
        "context": "Urban warfare favors defenders who can use buildings, tunnels, and civilian terrain for concealment.",
        "expected_victor": "Uncertain — depends on supply and morale",
        "notes": "Urban terrain neutralizes attacker's numerical and technological advantages significantly.",
    },
    "naval_dominance": {
        "name": "Naval Dominance Campaign",
        "description": "Naval power projection against an inferior maritime force to achieve sea control and enable amphibious operations.",
        "attacker_strategy": "Naval",
        "defender_strategy": "Conventional",
        "terrain": "Sea",
        "force_ratio": 2.0,
        "technology_gap": 1.0,
        "supply_lines": 0.95,
        "morale": 0.8,
        "weather": "Clear",
        "historical_examples": [
            "Battle of Midway (1942)",
            "Falklands War naval campaign (1982)",
            "Battle of Trafalgar (1805)",
            "Battle of Leyte Gulf (1944)",
        ],
        "context": "Naval superiority enables trade blockades, amphibious landings, and strategic bombardment of coastal targets.",
        "expected_victor": "Attacker",
        "notes": "Naval technology gap is decisive at sea. Submarine and air threats can level playing field.",
    },
    "coalition_vs_empire": {
        "name": "Coalition Against Hegemonic Power",
        "description": "Multi-nation coalition forms to resist an overextended hegemonic empire attempting to maintain control.",
        "attacker_strategy": "Coalition",
        "defender_strategy": "Conventional",
        "terrain": "Plains",
        "force_ratio": 1.2,
        "technology_gap": -0.5,
        "supply_lines": 0.65,
        "morale": 0.8,
        "weather": "Clear",
        "historical_examples": [
            "Coalition Wars against Napoleon",
            "Allied Coalition in WWI against Central Powers",
            "Gulf War Coalition vs Iraq",
            "Anti-Hitler Allied Coalition in WWII",
        ],
        "context": "Coalitions combine military, economic, and diplomatic resources but face coordination challenges.",
        "expected_victor": "Coalition",
        "notes": "Coalition's combined resources offset technology disadvantage. Coordination friction is the key weakness.",
    },
    "attrition_war": {
        "name": "War of Attrition in Mountains",
        "description": "Prolonged attritional campaign in mountainous terrain where both sides bleed each other over extended time.",
        "attacker_strategy": "Attrition",
        "defender_strategy": "Guerrilla",
        "terrain": "Mountains",
        "force_ratio": 3.0,
        "technology_gap": 1.0,
        "supply_lines": 0.5,
        "morale": 0.6,
        "weather": "Snow",
        "historical_examples": [
            "Soviet-Afghan War (1979-1989)",
            "Battle of Verdun (1916)",
            "Italian Campaign WWI Isonzo battles",
            "Korean War mountain battles (1951-53)",
        ],
        "context": "Mountain terrain favors defenders and guerrillas. Attrition by a larger force faces supply and morale challenges.",
        "expected_victor": "Defender (Guerrilla)",
        "notes": "Mountain terrain, poor supply lines, and defender morale advantage typically overcome numerical superiority.",
    },
    "desert_blitz": {
        "name": "Desert Armored Warfare",
        "description": "Fast-moving armored and air combined operations in open desert terrain.",
        "attacker_strategy": "Blitzkrieg",
        "defender_strategy": "Attrition",
        "terrain": "Desert",
        "force_ratio": 1.3,
        "technology_gap": 1.0,
        "supply_lines": 0.8,
        "morale": 0.75,
        "weather": "Clear",
        "historical_examples": [
            "North African Campaign 1941-43",
            "Six-Day War Sinai operations",
            "Gulf War ground campaign 1991",
            "Yom Kippur War Sinai battles",
        ],
        "context": "Desert favors mobile warfare and precision air power. Logistics is the decisive constraint.",
        "expected_victor": "Attacker",
        "notes": "Desert terrain maximizes blitzkrieg effectiveness. Supply lines and air superiority are critical.",
    },
    "deception_campaign": {
        "name": "Strategic Deception Operation",
        "description": "One side uses elaborate deception to mask the true direction of their main attack.",
        "attacker_strategy": "Deception",
        "defender_strategy": "Conventional",
        "terrain": "Plains",
        "force_ratio": 0.9,
        "technology_gap": 0.0,
        "supply_lines": 0.85,
        "morale": 0.9,
        "weather": "Clear",
        "historical_examples": [
            "Operation Overlord/Fortitude (D-Day deception 1944)",
            "Maskirovka at Battle of Kursk",
            "Battle of Midway (US deception about fleet location)",
            "Trojan Horse (mythological paradigm)",
        ],
        "context": "Deception can overcome numerical or technological disadvantages by creating decisive surprise.",
        "expected_victor": "Attacker",
        "notes": "Success hinges on intelligence penetration. Once deception is discovered, advantage disappears.",
    },
    "psychological_warfare": {
        "name": "Psychological Warfare Campaign",
        "description": "Targeting enemy morale through propaganda, terror, and symbolic victories to erode will to fight.",
        "attacker_strategy": "Psychological",
        "defender_strategy": "Attrition",
        "terrain": "Urban",
        "force_ratio": 0.7,
        "technology_gap": -0.5,
        "supply_lines": 0.7,
        "morale": 0.95,
        "weather": "Clear",
        "historical_examples": [
            "Tet Offensive (1968) psychological impact",
            "Mongol terror campaigns",
            "IRA bombing campaigns",
            "ISIS media and terror strategy",
        ],
        "context": "Psychological warfare targets political will rather than military forces. Media amplification is critical.",
        "expected_victor": "Uncertain",
        "notes": "Effectiveness depends on enemy political cohesion and public support for the war.",
    },
    "flanking_maneuver": {
        "name": "Classic Flanking Envelopment",
        "description": "Attacking enemy flanks and rear while pinning the front, seeking complete encirclement.",
        "attacker_strategy": "Flanking",
        "defender_strategy": "Conventional",
        "terrain": "Plains",
        "force_ratio": 1.1,
        "technology_gap": 0.0,
        "supply_lines": 0.9,
        "morale": 0.85,
        "weather": "Clear",
        "historical_examples": [
            "Battle of Cannae (216 BC)",
            "Battle of Marathon flanking attack",
            "Operation Bagration flanking of Army Group Centre (1944)",
            "Battle of Tannenberg (1914)",
        ],
        "context": "The double envelopment is the most decisive battlefield tactic in history. Requires superior coordination.",
        "expected_victor": "Attacker",
        "notes": "Flanking requires cavalry/armor superiority or superior mobility. Defended flanks neutralize this approach.",
    },
}

# Strategy counter-relationships (historical effectiveness)
STRATEGY_COUNTERS: Dict[str, Dict[str, float]] = {
    "Guerrilla": {
        "Conventional": 1.3,
        "Attrition": 0.8,
        "Psychological": 0.9,
        "Siege": 1.2,
        "Blitzkrieg": 1.4,
        "Flanking": 1.1,
        "Deception": 0.95,
        "Naval": 1.5,
        "Coalition": 0.85,
        "Guerrilla": 1.0,
    },
    "Blitzkrieg": {
        "Conventional": 1.4,
        "Attrition": 1.2,
        "Guerrilla": 0.7,
        "Siege": 1.3,
        "Flanking": 1.0,
        "Deception": 0.9,
        "Naval": 1.1,
        "Psychological": 1.1,
        "Coalition": 0.85,
        "Blitzkrieg": 1.0,
    },
    "Attrition": {
        "Blitzkrieg": 0.85,
        "Guerrilla": 1.2,
        "Conventional": 1.1,
        "Siege": 0.9,
        "Flanking": 0.85,
        "Deception": 0.9,
        "Naval": 1.0,
        "Psychological": 1.1,
        "Coalition": 0.8,
        "Attrition": 1.0,
    },
    "Siege": {
        "Conventional": 1.2,
        "Attrition": 1.1,
        "Guerrilla": 0.8,
        "Blitzkrieg": 0.7,
        "Flanking": 0.9,
        "Deception": 0.95,
        "Naval": 0.7,
        "Psychological": 1.0,
        "Coalition": 0.9,
        "Siege": 1.0,
    },
    "Flanking": {
        "Conventional": 1.3,
        "Siege": 1.2,
        "Attrition": 1.15,
        "Guerrilla": 0.8,
        "Blitzkrieg": 1.0,
        "Deception": 0.9,
        "Naval": 0.9,
        "Psychological": 1.0,
        "Coalition": 0.95,
        "Flanking": 1.0,
    },
    "Deception": {
        "Conventional": 1.3,
        "Blitzkrieg": 1.1,
        "Attrition": 1.0,
        "Guerrilla": 1.05,
        "Siege": 1.05,
        "Flanking": 1.1,
        "Naval": 1.1,
        "Psychological": 1.0,
        "Coalition": 1.0,
        "Deception": 1.0,
    },
    "Naval": {
        "Conventional": 1.2,
        "Siege": 1.1,
        "Blitzkrieg": 0.9,
        "Attrition": 1.0,
        "Guerrilla": 0.7,
        "Flanking": 1.0,
        "Deception": 0.9,
        "Psychological": 0.9,
        "Coalition": 1.0,
        "Naval": 1.0,
    },
    "Psychological": {
        "Conventional": 1.2,
        "Attrition": 0.95,
        "Blitzkrieg": 0.9,
        "Guerrilla": 1.05,
        "Siege": 1.0,
        "Flanking": 1.0,
        "Deception": 1.0,
        "Naval": 1.1,
        "Coalition": 1.15,
        "Psychological": 1.0,
    },
    "Coalition": {
        "Conventional": 1.3,
        "Blitzkrieg": 1.2,
        "Attrition": 1.25,
        "Guerrilla": 1.15,
        "Siege": 1.1,
        "Flanking": 1.05,
        "Deception": 1.0,
        "Naval": 1.0,
        "Psychological": 0.85,
        "Coalition": 1.0,
    },
    "Conventional": {
        "Guerrilla": 0.75,
        "Blitzkrieg": 0.7,
        "Attrition": 0.9,
        "Siege": 0.85,
        "Flanking": 0.8,
        "Deception": 0.75,
        "Naval": 0.85,
        "Psychological": 0.85,
        "Coalition": 0.75,
        "Conventional": 1.0,
    },
}

# Terrain advantage multipliers for each strategy
TERRAIN_MULTIPLIERS: Dict[str, Dict[str, float]] = {
    "Guerrilla": {"Mountains": 1.3, "Forest": 1.25, "Urban": 1.15, "Plains": 0.7, "Desert": 0.9, "Sea": 0.4},
    "Blitzkrieg": {"Plains": 1.3, "Desert": 1.25, "Forest": 0.75, "Mountains": 0.6, "Urban": 0.8, "Sea": 0.5},
    "Conventional": {"Plains": 1.15, "Desert": 1.1, "Mountains": 0.8, "Forest": 0.85, "Urban": 0.9, "Sea": 0.7},
    "Naval": {"Sea": 1.5, "Plains": 0.5, "Desert": 0.4, "Mountains": 0.3, "Forest": 0.4, "Urban": 0.6},
    "Siege": {"Urban": 1.25, "Mountains": 1.0, "Plains": 0.9, "Desert": 0.85, "Forest": 0.8, "Sea": 0.5},
    "Attrition": {"Mountains": 1.1, "Forest": 1.05, "Urban": 1.15, "Plains": 0.95, "Desert": 0.9, "Sea": 0.85},
    "Flanking": {"Plains": 1.2, "Desert": 1.15, "Forest": 0.85, "Mountains": 0.75, "Urban": 0.9, "Sea": 0.8},
    "Deception": {"Urban": 1.15, "Forest": 1.1, "Mountains": 1.05, "Plains": 1.0, "Desert": 0.95, "Sea": 0.9},
    "Psychological": {"Urban": 1.1, "Plains": 1.0, "Forest": 0.95, "Mountains": 0.9, "Desert": 0.95, "Sea": 0.85},
    "Coalition": {"Plains": 1.1, "Desert": 1.05, "Sea": 1.05, "Mountains": 0.95, "Forest": 0.9, "Urban": 1.0},
}
