FROM python:3.8-slim

# Set the working directory inside the container
WORKDIR /app/collection
# Copy only the requirements.txt file to the container, to optimize build caching
COPY ./requirements.txt ./requirements.txt
# Install the Python packages listed in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

RUN adduser --disabled-password --gecos '' appuser
USER appuser

# Command to run when the container starts
CMD ["python", "-u", "main.py"]
