"""Legal Intelligence Agent - Specializes in Constitutional and Legislative research."""

from typing import Any

import structlog

from app.agents.base_agent import BaseAgent
from app.core.config import get_settings
from app.services.memory.vector_store import VectorStore

logger = structlog.get_logger(__name__)


class LegalAgent(BaseAgent):
    """Agent for constitutional research, citation-backed answers, and legal analysis."""

    def __init__(self):
        super().__init__(
            name="LegalAgent",
            description="Expert in Constitutional Law and Legislative research for DISHA",
        )
        self.settings = get_settings()
        self.vector_store = VectorStore(collection_name="legal_knowledge")
        self._llm = None

    def _get_llm(self):
        """Get or create LLM instance."""
        if self._llm is None:
            from langchain_openai import ChatOpenAI

            self._llm = ChatOpenAI(
                model=self.settings.LLM_MODEL,
                temperature=0.0,
                api_key=self.settings.OPENAI_API_KEY,
            )
        return self._llm

    async def execute(
        self, target: str, options: dict[str, Any] | None = None
    ) -> dict[str, Any]:
        """Research constitutional provisions and provide cited analysis."""
        options = options or {}
        query = target
        n_results = options.get("n_results", 5)

        provisions = await self.vector_store.query(query, n_results=n_results)

        if not provisions:
            return {
                "query": query,
                "analysis": "No specific constitutional provisions found for this query in the current knowledge base.",
                "provisions": [],
                "disclaimer": self._get_disclaimer(),
            }

        context = "\n\n".join(
            [
                f"Source: {p['metadata'].get('source', 'Constitution of India')}\n"
                f"Article/Section: {p['metadata'].get('article', 'N/A')}\n"
                f"Content: {p['document']}"
                for p in provisions
            ]
        )

        prompt = self._build_legal_prompt(query, context)
        analysis = await self._generate_analysis(prompt)

        return {
            "query": query,
            "analysis": analysis,
            "provisions": [p["metadata"] for p in provisions],
            "citations": [
                p["metadata"].get("article")
                for p in provisions
                if p["metadata"].get("article")
            ],
            "disclaimer": self._get_disclaimer(),
        }

    def _build_legal_prompt(self, query: str, context: str) -> str:
        """Build a strict legal analysis prompt."""
        return f"""
You are the DISHA Legal Expert, a precision-oriented AI specializing in the Constitution of India.
Your task is to answer the user's query based EXCLUSIVELY on the provided constitutional context.

### User Query:
{query}

### Constitutional Context:
{context}

### Instructions:
1. Provide a clear, authoritative answer based on the context.
2. Cite the specific Article or Section for every claim.
3. If the context does not contain the answer, state that "The current constitutional dataset does not provide enough information to answer this precisely."
4. Do not offer personal legal advice.
5. Maintain a professional, neutral, and academic tone.

### Response Format:
Summary: [One sentence high-level answer]
Analysis: [Detailed explanation with citations]
Key Articles: [Comma-separated list of mentioned Articles]
"""

    async def _generate_analysis(self, prompt: str) -> str:
        """Generate analysis using the LLM."""
        try:
            llm = self._get_llm()
            response = await llm.ainvoke(prompt)
            return response.content
        except Exception as e:
            self.logger.error("legal_analysis_failed", error=str(e))
            return f"Legal processing failed: {str(e)}"

    def _get_disclaimer(self) -> str:
        """Mandatory disclaimer for legal outputs."""
        return (
            "DISCLAIMER: This information is generated by the DISHA Legal Agent for educational and research purposes only. "
            "It does not constitute legal advice. High-stakes legal decisions should be verified by a qualified legal professional "
            "against official Government of India gazettes and publications."
        )
