"""Pydantic schemas for API request/response models."""

from pydantic import BaseModel, Field
from typing import Optional, Any
from datetime import datetime, timezone
from enum import Enum


class InvestigationType(str, Enum):
    """Types of investigations supported."""
    OSINT = "osint"
    CRYPTO = "crypto"
    THREAT = "threat"
    FULL = "full"


class InvestigationRequest(BaseModel):
    """Request model for starting an investigation."""
    target: str = Field(..., description="Target entity to investigate (IP, domain, wallet, etc.)")
    investigation_type: InvestigationType = Field(default=InvestigationType.FULL)
    depth: int = Field(default=2, ge=1, le=5, description="Investigation depth level")
    options: dict[str, Any] = Field(default_factory=dict)


class MultiInvestigationRequest(BaseModel):
    """Request for investigating multiple targets."""
    targets: list[str] = Field(..., min_length=1, max_length=20)
    investigation_type: InvestigationType = Field(default=InvestigationType.FULL)
    depth: int = Field(default=2, ge=1, le=5)


class EntityNode(BaseModel):
    """An entity node in the knowledge graph."""
    id: str
    label: str
    entity_type: str
    properties: dict[str, Any] = Field(default_factory=dict)
    risk_score: float = Field(default=0.0, ge=0.0, le=1.0)


class EntityRelationship(BaseModel):
    """A relationship between entities."""
    source_id: str
    target_id: str
    relationship_type: str
    properties: dict[str, Any] = Field(default_factory=dict)
    confidence: float = Field(default=1.0, ge=0.0, le=1.0)


class InvestigationResult(BaseModel):
    """Result of an investigation."""
    investigation_id: str
    target: str
    investigation_type: InvestigationType
    status: str = "completed"
    entities: list[EntityNode] = Field(default_factory=list)
    relationships: list[EntityRelationship] = Field(default_factory=list)
    anomalies: list[dict[str, Any]] = Field(default_factory=list)
    risk_score: float = Field(default=0.0, ge=0.0, le=1.0)
    summary: str = ""
    raw_data: dict[str, Any] = Field(default_factory=dict)
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class AlertLevel(str, Enum):
    """Alert severity levels."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class Alert(BaseModel):
    """An alert generated by the system."""
    alert_id: str
    level: AlertLevel
    title: str
    description: str
    source: str
    entity_id: Optional[str] = None
    metadata: dict[str, Any] = Field(default_factory=dict)
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class GraphInsightRequest(BaseModel):
    """Request for graph-based insights."""
    entity_id: Optional[str] = None
    insight_type: str = Field(default="community", description="Type: community, link_prediction, centrality")
    limit: int = Field(default=10, ge=1, le=100)


class GraphInsightResponse(BaseModel):
    """Response containing graph insights."""
    insight_type: str
    results: list[dict[str, Any]] = Field(default_factory=list)
    metadata: dict[str, Any] = Field(default_factory=dict)


class AuthRequest(BaseModel):
    """Authentication request."""
    email: str
    password: str


class AuthResponse(BaseModel):
    """Authentication response."""
    access_token: str
    token_type: str = "bearer"
    user_id: str


class HealthResponse(BaseModel):
    """Health check response."""
    status: str = "healthy"
    version: str
    services: dict[str, str] = Field(default_factory=dict)
